gripper_controller:
  type: position_controllers/GripperActionController
  joint: robotiq_85_left_knuckle_joint

# joint_trajectory_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - robotiq_85_left_knuckle_joint
