<?xml version="1.0"?>
<robot name="mars_lite" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Mobile platform properties -->
  <xacro:property name="mob_base_length" value="0.780"/>
  <xacro:property name="mob_base_width" value="0.510"/>
  <xacro:property name="mob_base_height" value="0.37"/>
  <xacro:property name="wheel_radius" value="0.1016"/>
  <xacro:property name="wheels_distance" value="0.393"/>
  <xacro:property name="base_to_wheels_axel" value="0.01045"/>
  <xacro:property name="mob_base_lower_plate_length" value="0.630"/>

  <!-- arm positioning -->
  <xacro:property name="tm_x_offset" value="0.350"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="lightgrey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://mars_lite_description/meshes/mob_plat.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="${mob_base_length/2-mob_base_lower_plate_length/2} 0 ${mob_base_height/2}"/>
      <geometry>
        <box size="${mob_base_length} ${mob_base_width} ${mob_base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mars_lite_description/meshes/wheel.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.03"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="1"/>
    </link>
    <joint name="${prefix}_wheel" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${reflect*wheels_distance/2} 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheel prefix="right" reflect="-1"/>
  <xacro:wheel prefix="left" reflect="1"/>
  
  <!-- tm -->
  <xacro:include filename="$(find tm_description)/urdf/tm700.urdf.xacro"/>
  <!-- arm -->
  <xacro:tm700_robot prefix="tm_" joint_limited="true"/>

  <joint name="base_link_to_tm_base_link" type="fixed">
    <parent link="base_link" />
    <child link = "tm_base" />
    <origin xyz="${tm_x_offset} 0.0 ${mob_base_height}" rpy="0.0 0.0 0.0" />
  </joint>

</robot>