<?xml version="1.0"?>
<robot name="mars_lite" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Gazebo plugin -->
  <xacro:include filename="$(find mars_lite_description)/urdf/mars_lite.gazebo" />

  <!-- Inertia matrices -->
  <xacro:include filename="$(find mars_lite_description)/urdf/macros.xacro" />


  <!-- Mobile platform properties -->
  <xacro:property name="mob_base_length" value="0.780"/>
  <xacro:property name="mob_base_width" value="0.510"/>
  <xacro:property name="mob_base_height" value="0.37"/>
  <xacro:property name="wheel_radius" value="0.1016"/>
  <xacro:property name="wheels_distance" value="0.393"/>
  <xacro:property name="base_to_wheels_axel" value="0.01045"/>
  <xacro:property name="mob_base_lower_plate_length" value="0.630"/>

  <!-- TM5 robot arm contrl box properties -->
  <xacro:property name="tm_cntrl_box_length" value="0.29"/>
  <xacro:property name="tm_cntrl_box_width" value="0.43"/>
  <xacro:property name="tm_cntrl_box_height" value="0.23"/>
  <xacro:property name="tm_cntrl_box_x_offset" value="-0.125"/>

  <!-- arm positioning -->
  <xacro:property name="tm_x_offset" value="0.350"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="lightgrey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>


  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://mars_lite_description/meshes/mob_plat.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${mob_base_height/2 - wheel_radius * 0.5}" rpy="0 0 0"/>
      <geometry>
        <box size="${mob_base_lower_plate_length} ${mob_base_width} ${mob_base_height + wheel_radius * 1.0}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${mob_base_height/2 - wheel_radius * 0.5}" rpy="0 0 0" />
      <mass value="80.0" />
      <xacro:box_inertia m="80.0" x="${mob_base_lower_plate_length}" y="${mob_base_width}" z="${mob_base_height + wheel_radius * 1.0}" />
    </inertial>
  </link>

  <!-- Dummy footprint link -->
  <!-- <link name="base_footprint" />
  <joint name="footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="base_link"/>
  </joint> -->



  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mars_lite_description/meshes/wheel.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.03"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="10" />
        <xacro:cylinder_inertia m="10" r="${wheel_radius}" h="0.03" />
      </inertial>
    </link>
    <joint name="${prefix}_wheel" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${reflect*wheels_distance/2} 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheel prefix="right" reflect="-1"/>
  <xacro:wheel prefix="left" reflect="1"/>


  <!-- Robot arm contrl box -->
  <link name="tm_cntrl_box">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${tm_cntrl_box_length} ${tm_cntrl_box_width} ${tm_cntrl_box_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5.0" />
      <xacro:box_inertia m="5.0" x="${tm_cntrl_box_length}" y="${tm_cntrl_box_width}" z="${tm_cntrl_box_height}" />
    </inertial>
  </link>
  <joint name="base_link_to_cntrl_box" type="fixed">
      <axis xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="tm_cntrl_box"/>
      <origin xyz="${tm_cntrl_box_x_offset} 0 ${mob_base_height + tm_cntrl_box_height/2}" rpy="0 0 0"/>
  </joint>


  <!-- tm5_700 gazebo common stuff -->
  <xacro:include filename="$(find tm5_description)/urdf/common.gazebo.xacro" />
  <!-- tm5_700 -->
  <xacro:include filename="$(find tm5_description)/urdf/tm5_700.urdf.xacro" />
  <xacro:tm5_700_robot prefix="tm_" joint_limited="true" stl_mesh="true" />

  <joint name="base_link_to_tm_base_link" type="fixed">
    <parent link="base_link" />
    <child link = "tm_base" />
    <origin xyz="${tm_x_offset} 0.0 ${mob_base_height}" rpy="0.0 0.0 0.0" />
  </joint>


  <!-- Robotiq 85 gripper -->
  <xacro:include filename="$(find robotiq_description)/urdf/robotiq_85_gripper.urdf.xacro" />
  <xacro:robotiq_85_gripper prefix="" parent="tm_flange_link" >
    <origin xyz="0 0 0" rpy="${-pi / 2} ${-pi / 2} 0"/>
  </xacro:robotiq_85_gripper>

</robot>