controller_list:
  - name: fake_tm_arm_controller
    joints:
      - tm_shoulder_1_joint
      - tm_shoulder_2_joint
      - tm_elbow_joint
      - tm_wrist_1_joint
      - tm_wrist_2_joint
      - tm_wrist_3_joint