# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: tm_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint
    # - gripper_right_driver_joint
    - left_wheel
    - right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint
  gains:
    tm_shoulder_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tm_shoulder_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tm_elbow_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
wheel_effort_controller:
  type: effort_controllers/JointVelocityController
  joints:
    - left_wheel
    - right_wheel
  gains:
    left_wheel:
      p: 1.0
      i: 0.1
      d: 1.0
    right_wheel:
      p: 1.0
      i: 0.1
      d: 1.0

gazebo_ros_control:   
  pid_gains:
    left_wheel:
      p: 100.0
      i: 0.01 
      d: 10.0
    right_wheel:
      p: 100.0
      i: 0.01 
      d: 10.0